/*
  Warnings:

  - The values [UNDER_QA_REVIEW,QA_NEEDS_CORRECTION] on the enum `ReportStatus` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ReportStatus_new" AS ENUM ('DRAFT', 'SUBMITTED_BY_CLIENT', 'CLIENT_NEEDS_PRELIMINARY_CORRECTION', 'CLIENT_NEEDS_FINAL_CORRECTION', 'UNDER_CLIENT_PRELIMINARY_CORRECTION', 'UNDER_CLIENT_FINAL_CORRECTION', 'PRELIMINARY_RESUBMISSION_BY_CLIENT', 'FINAL_RESUBMISSION_BY_CLIENT', 'UNDER_CLIENT_PRELIMINARY_REVIEW', 'UNDER_CLIENT_FINAL_REVIEW', 'RECEIVED_BY_FRONTDESK', 'FRONTDESK_ON_HOLD', 'FRONTDESK_NEEDS_CORRECTION', 'UNDER_PRELIMINARY_TESTING_REVIEW', 'PRELIMINARY_TESTING_ON_HOLD', 'PRELIMINARY_TESTING_NEEDS_CORRECTION', 'PRELIMINARY_RESUBMISSION_BY_TESTING', 'UNDER_PRELIMINARY_RESUBMISSION_TESTING_REVIEW', 'PRELIMINARY_APPROVED', 'UNDER_FINAL_TESTING_REVIEW', 'FINAL_TESTING_ON_HOLD', 'FINAL_TESTING_NEEDS_CORRECTION', 'FINAL_RESUBMISSION_BY_TESTING', 'UNDER_FINAL_RESUBMISSION_TESTING_REVIEW', 'UNDER_QA_PRELIMINARY_REVIEW', 'QA_NEEDS_PRELIMINARY_CORRECTION', 'UNDER_QA_FINAL_REVIEW', 'QA_NEEDS_FINAL_CORRECTION', 'UNDER_FINAL_RESUBMISSION_QA_REVIEW', 'UNDER_ADMIN_REVIEW', 'ADMIN_NEEDS_CORRECTION', 'ADMIN_REJECTED', 'UNDER_FINAL_RESUBMISSION_ADMIN_REVIEW', 'FINAL_APPROVED', 'LOCKED');
ALTER TABLE "MicroMixDetails" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "MicroMixWaterDetails" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Report" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Report" ALTER COLUMN "status" TYPE "ReportStatus_new" USING ("status"::text::"ReportStatus_new");
ALTER TABLE "MicroMixDetails" ALTER COLUMN "status" TYPE "ReportStatus_new" USING ("status"::text::"ReportStatus_new");
ALTER TABLE "MicroMixWaterDetails" ALTER COLUMN "status" TYPE "ReportStatus_new" USING ("status"::text::"ReportStatus_new");
ALTER TABLE "StatusHistory" ALTER COLUMN "from" TYPE "ReportStatus_new" USING ("from"::text::"ReportStatus_new");
ALTER TABLE "StatusHistory" ALTER COLUMN "to" TYPE "ReportStatus_new" USING ("to"::text::"ReportStatus_new");
ALTER TYPE "ReportStatus" RENAME TO "ReportStatus_old";
ALTER TYPE "ReportStatus_new" RENAME TO "ReportStatus";
DROP TYPE "ReportStatus_old";
ALTER TABLE "MicroMixDetails" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "MicroMixWaterDetails" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
ALTER TABLE "Report" ALTER COLUMN "status" SET DEFAULT 'DRAFT';
COMMIT;
