-- AlterEnum
ALTER TYPE "ChemistryReportStatus" ADD VALUE 'UNDER_RESUBMISSION_QA_REVIEW';

-- AlterEnum
ALTER TYPE "ReportStatus" ADD VALUE 'UNDER_FINAL_RESUBMISSION_QA_REVIEW';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "lastActivityAt" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastLoginAt" SET DATA TYPE TIMESTAMP(6);
