/*
  Warnings:

  - The values [MICRO_GENERAL,MICRO_GENERAL_WATER] on the enum `FormType` will be removed.
*/

-- Safety check: ensure no rows still use the soon-to-be-removed enum variants.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM "Report"
    WHERE "formType" IN ('MICRO_GENERAL','MICRO_GENERAL_WATER')
  ) THEN
    RAISE EXCEPTION
      'Cannot drop enum variants while rows still use MICRO_GENERAL / MICRO_GENERAL_WATER';
  END IF;
END $$;

-- AlterEnum (generated by Prisma) — OK to keep
BEGIN;
CREATE TYPE "FormType_new" AS ENUM ('MICRO_MIX', 'MICRO_MIX_WATER');
ALTER TABLE "Report" ALTER COLUMN "formType" TYPE "FormType_new"
  USING ("formType"::text::"FormType_new");
ALTER TYPE "FormType" RENAME TO "FormType_old";
ALTER TYPE "FormType_new" RENAME TO "FormType";
DROP TYPE "FormType_old";
COMMIT;

-- NOTE: Remove FK drops against non-existent tables
-- ALTER TABLE "MicroGeneralDetails" DROP CONSTRAINT "MicroGeneralDetails_reportId_fkey";
-- ALTER TABLE "MicroGeneralWaterDetails" DROP CONSTRAINT "MicroGeneralWaterDetails_reportId_fkey";

-- Add columns to User (idempotent)
ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "lastActivityAt" TIMESTAMPTZ(6),
  ADD COLUMN IF NOT EXISTS "lastLoginAt"    TIMESTAMPTZ(6);

-- Drop legacy tables if they exist (idempotent)
DROP TABLE IF EXISTS "MicroGeneralDetails";
DROP TABLE IF EXISTS "MicroGeneralWaterDetails";
