# fly.staging.toml
app = "omega-lims-staging"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "uploads"
  destination = "/data/uploads"

[deploy]
  # Run Prisma migrations then seed on deploy
  release_command = "sh -c 'npx prisma migrate deploy && npx prisma db seed'"

